### ISSUE TITLE
c-to-ll.sh  script generates optimized code

### ISSUE THREAD

**Issue by charliekarel** [snu-sf-class/swpp202101-benchmarks#1]
I tried using the script above to generate IR code from C file but it seems to me that there is a fair amount of optimization from the original C code, including some of the optimizations that we would like to implement, is this how the script is supposed to function, if yes, can we turn off the optimization?

**Comment by aqjune** [comment]
I suppose there are still room for improvement.
For example, accessing the same memory address twice in a short period is costly due to the temperature.
To address this, making the interval between such accesses longer or inserting `cool` will be helpful.
Also, many of the optimizations listed in `optList.md` are not applied yet; please apply them properly to get a better code.
